<div class="pallates-switcher">
    <div class="face_swatch_switch" style="display: none">
        <a href="javascript:void(0)">
            Face Swatch
        </a>
    </div>
    <div class="eye_swatch_switch" style="display: none">
        <a href="javascript:void(0)">
            Eye Swatch
        </a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".swatch-attribute-options.clearfix": {
            "optionswitcher": {}
        }
    }
</script>