<div class="instruction">
    <span>DRAG & DROP SHADES TO PALETTE</span>
</div>
<div class="pallates-switcher">
    <div class="face_swatch_switch" style="display: none">
        <a href="javascript:void(0)">
            Sheer Face Color
        </a>
    </div>
    <div class="eye_swatch_switch" style="display: none">
        <a href="javascript:void(0)">
            Eye Color
        </a>
    </div>
	<span class="swatch-attribute-label">Color: </span>
</div>
<script type="text/x-magento-init">
    {
        ".swatch-attribute-options.clearfix": {
            "optionswitcher": {}
        }
    }
</script>
