<?php
$closeButtonImageUrl = $block->getData('close_image');
?>
<div class="pallet-image col-six" >
    <img src="<?= $block->getData('pallet_image') ?>">
    <table>
        <tr>
            <td>
                <div class="circle_eye" id="eye_color_1" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye" id="eye_color_2">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td><div class="circle_eye" id="eye_color_3">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="circle_eye" id="eye_color_4" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye" id="eye_color_5">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye" id="eye_color_6" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
        </tr>
    </table>
</div>