<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$palletType = $_product->getResource()->getAttribute('custom_pallet_type')->getFrontend()->getValue($_product);
$palletType = str_replace(' ','',$palletType);
$eyeColorShade = 0;
$sheerFaceColorShade= 0;
switch ($palletType) {
    case '4wellPalette':
        $sheerFaceColorShade = 4;
        break;
    case '6wellPalette':
        $eyeColorShade = 6;
        break;
    case 'lgPalette':
        $eyeColorShade = 12;
        $sheerFaceColorShade = 6;
        break;
    case 'MK07-1Nudes':
        $eyeColorShade = 4;
        $sheerFaceColorShade = 3;
        break;
}
?>
<div class="product-add-form">
    <form data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
          action="<?= /* @NoEscape */ $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?php if($eyeColorShade != 0):?>
            <?php foreach (range(1,$eyeColorShade) as $i):?>
                 <input hidden="true" name="eye_color_<?= /* @escapeNotVerified */ $i ?>" id="eye_color_<?= /* @escapeNotVerified */ $i ?>" value="">
            <?php endforeach;?>
        <?php endif;?>
        <?php if($sheerFaceColorShade != 0):?>
            <?php foreach (range(1,$sheerFaceColorShade) as $i):?>
                <input hidden="true" name="sheer_face_<?= /* @escapeNotVerified */ $i ?>" id="sheer_face_<?= /* @escapeNotVerified */ $i ?>" value="">
            <?php endforeach;?>
        <?php endif;?>
        <?= $block->getBlockHtml('formkey') ?>
        <?= $block->getChildHtml('form_top') ?>
        <?php if (!$block->hasOptions()):?>
            <?= $block->getChildHtml('product_info_form_content') ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <?= $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>
        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?= $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?= $block->getChildHtml('form_bottom') ?>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>});
    });
</script>
