<?php
	$closeButtonImageUrl = $block->getData('close_image');
	$palletCount1 = 16;
	$palletCount2 = 6;
	$palletPerRow1 = 4;
	$palletPerRow2 = 2;
?>
<div class="pallets-media pallets-box--<?= $palletCount1;?>wellPalette" style="overflow:hidden;">
    <?php /*<div class="pallets-box__image"><img src="<?= $block->getData('pallet_image') ?>"></div>*/?>
	<div class="pallets-media__container <?= 'pallets-column-' .$palletPerRow1;?>" style="width:65%; float:left; padding-right: 20px;">
		<div class="pallets-media__items">
			<?php  
				for ($palletBox1 = 1; $palletBox1 <= $palletCount1; $palletBox1++) { ?>
					<div class="pallets-media__item"><div class="pallets-media__box">
						<img src="<?= $this->getViewFileUrl('Ec_CustomPallet/images/__blank.gif'); ?>" alt="blank" class="pallets-media__blank">
						<div class="circle_eye pallets-media__circle" id="<?php echo 'eye_color_'.$palletBox1;?>" >
							<img src="<?= $closeButtonImageUrl ?>" class="pallets-media__delete-pallet" style="visibility: hidden;">
						</div>
					</div>
					</div>
				<?php }
			?>
		</div>
	</div>

    <?php /*<div class="pallets-box__image"><img src="<?= $block->getData('pallet_image') ?>"></div>*/?>
	<div class="pallets-media__container <?= 'pallets-column-' .$palletPerRow2;?>" style="width:35%; padding-top: 2.5%; float:left;">
		<div class="pallets-media__items">
			<?php  
				for ($palletBox2 = 1; $palletBox2 <= $palletCount2; $palletBox2++) { ?>
					<div class="pallets-media__item"><div class="pallets-media__box">
						<img src="<?= $this->getViewFileUrl('Ec_CustomPallet/images/__blank.gif'); ?>" alt="blank" class="pallets-media__blank">
						<div class="circle_face pallets-media__circle" id="<?php echo 'sheer_face_'.$palletBox2;?>" >
							<img src="<?= $closeButtonImageUrl ?>" class="pallets-media__delete-pallet" style="visibility: hidden;">
						</div>
					</div>
					</div>
				<?php }
			?>
		</div>
	</div>
</div>

<?php /*<?php
$closeButtonImageUrl = $block->getData('close_image');
?>
<div class="pallet-image col-six" >
    <img src="<?= $block->getData('pallet_image') ?>">
    <table class="lgpallet_eye">
        <tr>
            <td>
                <div class="circle_eye " id="eye_color_1" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_2">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_3">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_4">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_5">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_6" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_7" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_8">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_9" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_10" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_11" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_12" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
        </tr>
    </table>
	
    <table class="lgpallet_face">
        <tr>
            <td>
                <div class="circle_face " id="sheer_face_1" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_face " id="sheer_face_2" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_face " id="sheer_face_3" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_face " id="sheer_face_4" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_face " id="sheer_face_5" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_face " id="sheer_face_6" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
        </tr>
    </table>
</div>*/?>