<?php
$closeButtonImageUrl = $block->getData('close_image');
?>
<div class="pallet-image" >
    <img src="<?= $block->getData('pallet_image') ?>">
    <table class="lgpallet_eye">
        <tr>
            <td>
                <div class="circle_eye " id="eye_color_1" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye" id="eye_color_2" >
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye" id="eye_color_3">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
            <td>
                <div class="circle_eye " id="eye_color_4">
                    <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
                </div>
            </td>
        </tr>
    </table>
    <table class="lgpallet_face">
        <td>
            <div class="circle_face" id="sheer_face_1" >
                <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
            </div>
        </td>
        <td>
            <div class="circle_face" id="sheer_face_2" >
                <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
            </div>
        </td>
        <td>
            <div class="circle_face" id="sheer_face_3" >
                <img src="<?= $closeButtonImageUrl ?>" style="visibility:hidden;width: 20px;height: 20px;" >
            </div>
        </td>
    </table>
</div>